CREATE TYPE "Role" AS ENUM (
  'ยังไม่ได้กำหนดสิทธิ์',
  'นักศึกษา',
  'อาจารย์'
);

CREATE TYPE "StatusPermissions" AS ENUM (
  'ยังไม่ยืนยัน',
  'ยืนยันแล้ว'
);

CREATE TYPE "StatusManageAccount" AS ENUM (
  'แก้ไขสิทธิ์แล้ว',
  'ลบบัญชีแล้ว'
);

CREATE TYPE "StatusQueueALL" AS ENUM (
  'รออนุมัติการจองคิว',
  'อนุมัติการจองคิวแล้ว',
  'เลื่อนการจองคิว',
  'ยกเลิกการจองคิว'
);

CREATE TABLE "AdminProfile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(20) NOT NULL,
  "password" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "LoginPermissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid_line" varchar(255) UNIQUE NOT NULL,
  "fullname" varchar(255) NOT NULL,
  "profile_image" varchar(255) NOT NULL,
  "status_permissions" "StatusPermissions",
  "role_user" "Role",
  "admin_id" integer,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ManageUserAccounts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status_permissions" "StatusPermissions",
  "status_ManageAccount" "StatusManageAccount",
  "admin_id" integer,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "StudentsProfile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "studentID" varchar(10) UNIQUE,
  "major" varchar(255),
  "login_permissionsID" integer,
  "manage_user_accountsID" integer,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Advisorsprofile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "academic_position" varchar(100),
  "major" varchar(255),
  "login_permissionsID" integer,
  "manage_user_accountsID" integer,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ConsultationTime" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultationDate" date NOT NULL,
  "consultation_start_time" time NOT NULL,
  "consultation_end_time" time NOT NULL,
  "advisors_profile_id" integer,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "QueueBooking" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_date" date NOT NULL,
  "booking_time" time NOT NULL,
  "consultation_type" varchar(100) NOT NULL,
  "problem_detail" text NOT NULL,
  "status_QueueBooking" "StatusQueueALL",
  "students_profile_id" integer,
  "advisors_profile_id" integer,
  "consultation_time_id" integer,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "CancelQueue" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Status_ManageQueue" "StatusQueueALL",
  "students_profile_id" integer,
  "advisors_profile_id" integer,
  "queue_booking_id" integer,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "QueuePostponement" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "old_date" date NOT NULL,
  "old_time" time NOT NULL,
  "Status_QueuePostponement" "StatusQueueALL",
  "students_profile_id" integer,
  "advisors_profile_id" integer,
  "queue_booking_id" integer,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "QueuePostponement_Students" (
  "reschedule_reason_Students" varchar(100) NOT NULL,
  "queue_postponement_id" integer NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "QueuePostponement_Advisors" (
  "reschedule_reason_Advisors" varchar(100) NOT NULL,
  "queue_postponement_id" integer NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN "LoginPermissions"."role_user" IS 'สิทธิ์การเข้าสู่ระบบ (ผู้ใช้ทั่วไป)';

ALTER TABLE "LoginPermissions" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("admin_id") REFERENCES "AdminProfile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ManageUserAccounts" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("admin_id") REFERENCES "AdminProfile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "StudentsProfile" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("login_permissionsID") REFERENCES "LoginPermissions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Advisorsprofile" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("login_permissionsID") REFERENCES "LoginPermissions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "StudentsProfile" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("manage_user_accountsID") REFERENCES "ManageUserAccounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Advisorsprofile" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("manage_user_accountsID") REFERENCES "ManageUserAccounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ConsultationTime" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("advisors_profile_id") REFERENCES "Advisorsprofile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QueueBooking" ADD CONSTRAINT "one_to_one" FOREIGN KEY ("students_profile_id") REFERENCES "StudentsProfile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QueueBooking" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("advisors_profile_id") REFERENCES "Advisorsprofile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QueueBooking" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("consultation_time_id") REFERENCES "ConsultationTime" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CancelQueue" ADD CONSTRAINT "one_to_one" FOREIGN KEY ("students_profile_id") REFERENCES "StudentsProfile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CancelQueue" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("advisors_profile_id") REFERENCES "Advisorsprofile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CancelQueue" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("queue_booking_id") REFERENCES "QueueBooking" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QueuePostponement" ADD CONSTRAINT "one_to_one" FOREIGN KEY ("students_profile_id") REFERENCES "StudentsProfile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QueuePostponement" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("advisors_profile_id") REFERENCES "Advisorsprofile" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QueuePostponement" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("queue_booking_id") REFERENCES "QueueBooking" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QueuePostponement_Students" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("queue_postponement_id") REFERENCES "QueuePostponement" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QueuePostponement_Advisors" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("queue_postponement_id") REFERENCES "QueuePostponement" ("id") DEFERRABLE INITIALLY IMMEDIATE;
