services:
  db:  # db คือชื่อ host ที่เราต้องเชื่อมเข้ากับ pgadmin4
    # ตัวรัน postgreSQL Database เลือกใช้เป็น postgresSQL version 15
    image: postgres:15 
    # ชื่อตัวเก็บ postgresSQL Database ตั้งเป็น (postgresSQL)
    container_name: postgresSQL
    # ตัวบังคับ restart container (เมื่อมีการเซตค่าผิดมันจะบังคับ restart ทันที)  
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Port ในการเชื่อมต่อ Database
    ports:
      - "5432:5432" 
    volumes:
        # หน่วยความจำ หรือ โฟรเดอร์ของฐานข้อมูล postgreSQL 
      - postgres_data:/var/lib/postgresql

  pgadmin:
    #  ตัวรัน PgAdmin สำหรับจัดการฐานข้อมูล 
    image: dpage/pgadmin4
    # ชื่อตัวเก็บ PgAdmin ตั้งเป็น (pgadmin4)
    container_name: pgadmin4 
    # ตัวบังคับ restart container (เมื่อมีการเซตค่าผิดมันจะบังคับ restart ทันที)  
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    # Port ในการเปิด PgAdmin 
    ports:
      - "8888:80"

volumes:
  postgres_data: # กำหนดชื่อ volumes ตามฐานข้อมูลเพื่อทำการสร้างหน่วยพื้นที่ในการเก็บให้กับฐานข้อมูลใน docker
    # จัดเก็บข้อมูลของฐานข้อมูลไว้ในเครื่องที่เราทำการโฮสอยู่
    driver: local # ระบุเรียกใช้ driver เป็นแบบ local