CREATE TYPE "Role" AS ENUM (
  'ผู้ดูแลระบบ',
  'นักศึกษา',
  'อาจารย์'
);

CREATE TYPE "StatusPermissions" AS ENUM (
  'ยังไม่ยืนยัน',
  'ยืนยันแล้ว'
);

CREATE TYPE "StatusManageAccount" AS ENUM (
  'แก้ไขสิทธิ์แล้ว',
  'ลบบัญชีแล้ว'
);

CREATE TYPE "StatusQueueALL" AS ENUM (
  'รออนุมัติการจองคิว',
  'อนุมัติการจองคิวแล้ว',
  'เลื่อนการจองคิว',
  'ยกเลิกการจองคิว'
);

CREATE TABLE "AdminProfile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(20) NOT NULL,
  "password" varchar(255) NOT NULL,
  "role_admin" "Role"
);

CREATE TABLE "LoginPermissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid_line" uuid NOT NULL,
  "fullname" varchar(255) NOT NULL,
  "profile_image" varchar(255) NOT NULL,
  "status_permissions" "StatusPermissions",
  "role_user" "Role",
  "admin_id" integer
);

CREATE TABLE "ManageUserAccounts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status_permissions" "StatusPermissions",
  "status_ManageAccount" "StatusManageAccount",
  "admin_id" integer
);

CREATE TABLE "StudentsProfile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "studentID" varchar(10),
  "major" varchar(255),
  "login_permissionsID" integer,
  "manage_user_accountsID" integer
);

CREATE TABLE "Advisorsprofile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "academic_position" varchar(100),
  "major" varchar(255),
  "login_permissionsID" integer,
  "manage_user_accountsID" integer
);

CREATE TABLE "ConsultationTime" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultationDate" date NOT NULL,
  "consultation_start_time" time NOT NULL,
  "consultation_end_time" time NOT NULL,
  "advisors_profile_id" integer
);

CREATE TABLE "QueueBooking" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_date" date NOT NULL,
  "booking_time" time NOT NULL,
  "consultation_type" varchar(100) NOT NULL,
  "problem_detail" text NOT NULL,
  "status_QueueBooking" "StatusQueueALL",
  "students_profile_id" integer,
  "advisors_profile_id" integer,
  "consultation_time_id" integer
);

CREATE TABLE "CancelQueue" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Status_ManageQueue" "StatusQueueALL",
  "students_profile_id" integer,
  "advisors_profile_id" integer,
  "queue_booking_id" integer
);

CREATE TABLE "QueuePostponement" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "old_date" date NOT NULL,
  "old_time" time NOT NULL,
  "Status_QueuePostponement" "StatusQueueALL",
  "students_profile_id" integer,
  "advisors_profile_id" integer,
  "queue_booking_id" integer
);

CREATE TABLE "QueuePostponement_Students" (
  "reschedule_reason_Students" varchar(100) NOT NULL,
  "queue_postponement_id" integer NOT NULL
);

CREATE TABLE "QueuePostponement_Advisors" (
  "reschedule_reason_Advisors" varchar(100) NOT NULL,
  "queue_postponement_id" integer NOT NULL
);

COMMENT ON COLUMN "AdminProfile"."role_admin" IS 'สิทธิ์การเข้าสู่ระบบ (ผู้ดูแลระบบ)';

COMMENT ON COLUMN "LoginPermissions"."role_user" IS 'สิทธิ์การเข้าสู่ระบบ (ผู้ใช้ทั่วไป)';

ALTER TABLE "LoginPermissions" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("admin_id") REFERENCES "AdminProfile" ("id");

ALTER TABLE "ManageUserAccounts" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("admin_id") REFERENCES "AdminProfile" ("id");

ALTER TABLE "StudentsProfile" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("login_permissionsID") REFERENCES "LoginPermissions" ("id");

ALTER TABLE "Advisorsprofile" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("login_permissionsID") REFERENCES "LoginPermissions" ("id");

ALTER TABLE "StudentsProfile" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("manage_user_accountsID") REFERENCES "ManageUserAccounts" ("id");

ALTER TABLE "Advisorsprofile" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("manage_user_accountsID") REFERENCES "ManageUserAccounts" ("id");

ALTER TABLE "ConsultationTime" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("advisors_profile_id") REFERENCES "Advisorsprofile" ("id");

ALTER TABLE "QueueBooking" ADD CONSTRAINT "one_to_one" FOREIGN KEY ("students_profile_id") REFERENCES "StudentsProfile" ("id");

ALTER TABLE "QueueBooking" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("advisors_profile_id") REFERENCES "Advisorsprofile" ("id");

ALTER TABLE "QueueBooking" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("consultation_time_id") REFERENCES "ConsultationTime" ("id");

ALTER TABLE "CancelQueue" ADD CONSTRAINT "one_to_one" FOREIGN KEY ("students_profile_id") REFERENCES "StudentsProfile" ("id");

ALTER TABLE "CancelQueue" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("advisors_profile_id") REFERENCES "Advisorsprofile" ("id");

ALTER TABLE "CancelQueue" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("queue_booking_id") REFERENCES "QueueBooking" ("id");

ALTER TABLE "QueuePostponement" ADD CONSTRAINT "one_to_one" FOREIGN KEY ("students_profile_id") REFERENCES "StudentsProfile" ("id");

ALTER TABLE "QueuePostponement" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("advisors_profile_id") REFERENCES "Advisorsprofile" ("id");

ALTER TABLE "QueuePostponement" ADD CONSTRAINT "many_to_one" FOREIGN KEY ("queue_booking_id") REFERENCES "QueueBooking" ("id");

ALTER TABLE "QueuePostponement_Students" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("queue_postponement_id") REFERENCES "QueuePostponement" ("id");

ALTER TABLE "QueuePostponement_Advisors" ADD CONSTRAINT "one_to_many" FOREIGN KEY ("queue_postponement_id") REFERENCES "QueuePostponement" ("id");
